[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["j.suess <jonas.suess@tum.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
